Add sonarcloud and jacoco
Lucia560/Jakarta_labb pull request #27
Opened 2024-02-25 16:03 UTC by Lucia560

I addeed SonarCloud and jacoco .I  also removed 2 dependencies , web socket and Jax rs that where already included in the jakarta enterprise dependency.

2024-02-25 18:36 UTC, marcusju23 requested changes
Great work! Some minor fix-ups then its good for merge! 👍

2024-02-25 18:36 UTC, marcusju23 commented on .github/workflows/sonarcloud.yml
> +
Remove reduntant space.

2024-02-25 18:36 UTC, marcusju23 commented on .github/workflows/sonarcloud.yml
> +
Remove redundant space from here and down.

2024-02-25 18:36 UTC, marcusju23 commented on pom.xml
> -    </dependency>
Remove commented out code.

2024-02-25 23:43 UTC, marcusju23 approved these changes

2024-02-25 23:54 UTC, marcusju23 approved these changes
Great work Lucia! The choice of the branch name was good as it contributes in quickly identifying the associated issue. As a minor enhancement, consider explicitly stating the issue(s) you are closing in your pull request(s). Keep it up! 👍

2024-02-26 09:17 UTC, TrungMa1 approved these changes
Nicely done Lucia! Overall, seems well-structured.

2024-02-26 10:32 UTC, merged